project_id = "mqnoszjhlotxqdjgubqt"

[functions.ai-mentor]
verify_jwt = false

[functions.subscription-email]
verify_jwt = false

[functions.get-user-email]
verify_jwt = false

[functions.check-expiring-subscriptions]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.interview-feedback]
verify_jwt = false
